// reactapp_vl/voltlines_aligassaloglu/src/components/SideBar.jsx
import React from 'react'
import { NavLink } from 'react-router-dom'
import MapIcon from '@mui/icons-material/Map';
import TableRowsIcon from '@mui/icons-material/TableRows';
import RouteIcon from '@mui/icons-material/Route';

const SideBar = function() {
    const sidebarData = [
        {
            title: "Create Order",
            icon: <MapIcon fontSize='inherit'/>,
            navigateTo: '/map-view'
        },
        {
            title: "Create ",
            icon: <TableRowsIcon fontSize='inherit'/>,
            navigateTo: '/table-view'
        },
        {
            title: "sads",
            icon: <RouteIcon fontSize='inherit'/>,
            navigateTo: '/route-details'
        }
    ]
    return (
    <div className='min-h-screen px-5 py-9 max-md:hidden'>
        <div className=' bg-slate-600 h-full  flex flex-col gap-2 px-5 py-4 rounded-2xl drop-shadow-xl justify-center' style={{backgroundColor: "#BED8D4"}}>
            {sidebarData.map((el)=>(
                <NavLink key={el.title} to={el.navigateTo} className={({isActive})=> isActive ? " flex flex-row text-4xl items-center justify-center gap-2 px-4 py-2 text-white" : " flex flex-row items-center justify-center gap-2 px-4 py-2  rounded-xl text-4xl"}>
                    {el.icon}
                </NavLink>
            ))}
        </div>
    </div>
  )
}

export default SideBar

// vueApp_vl/voltlines_pickup/src/components/SideBar.vue
<template>
<div class="  bg-lime-400 min-h-full rounded-2xl flex flex-col items-center justify-center text-4xl gap-9 text-slate-700">
    <router-link to="/" class="hover:text-white cursor-pointer">
        <font-awesome-icon icon="fa-solid fa-map-location" />
    </router-link>
    <router-link to="/table-view" class="hover:text-white cursor-pointer" >
        <font-awesome-icon icon="fa-solid fa-table" />
    </router-link>
    <router-link to="/route-details" class="hover:text-white cursor-pointer">
        <font-awesome-icon icon="fa-solid fa-route" />
    </router-link>
</div>
</template>
